/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SahajRouteImport } from './routes/sahaj'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtViewerRouteImport } from './routes/art-viewer'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SahajRoute = SahajRouteImport.update({
  id: '/sahaj',
  path: '/sahaj',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtViewerRoute = ArtViewerRouteImport.update({
  id: '/art-viewer',
  path: '/art-viewer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sahaj': typeof SahajRoute
  '/work': typeof WorkRoute
  '/art-viewer': typeof ArtViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sahaj': typeof SahajRoute
  '/work': typeof WorkRoute
  '/art-viewer': typeof ArtViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sahaj': typeof SahajRoute
  '/work': typeof WorkRoute
  '/art-viewer': typeof ArtViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/sahaj' | '/work' | '/art-viewer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/sahaj' | '/work' | '/art-viewer'
  id: '__root__' | '/' | '/contact' | '/sahaj' | '/work' | '/art-viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  SahajRoute: typeof SahajRoute
  WorkRoute: typeof WorkRoute
  ArtViewerRoute: typeof ArtViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sahaj': {
      id: '/sahaj'
      path: '/sahaj'
      fullPath: '/sahaj'
      preLoaderRoute: typeof SahajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-viewer': {
      id: '/art-viewer'
      path: '/art-viewer'
      fullPath: '/art-viewer'
      preLoaderRoute: typeof ArtViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  SahajRoute: SahajRoute,
  WorkRoute: WorkRoute,
  ArtViewerRoute: ArtViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
